// Auto-generated from services/agent-py/openapi.json. Do not edit by hand.
// Regenerate with: bun run codegen:agent-types
// See scripts/codegen-agent-types.sh for the rationale.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe — returns 200 as long as the process is up.
         *
         *     Does NOT depend on Supabase, the model gateway, or any other
         *     external service. A failing /healthz means restart the container;
         *     a failing /readyz means *don't route traffic yet* but the process
         *     might recover on its own.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe — reports configured dependencies.
         *
         *     Phase 0 only reported config presence; Phase 1 additionally
         *     reports whether the Postgres pool is open (which is the closest
         *     we get to "Postgres reachable" without a per-request `SELECT 1`).
         *     Phase 2+ may add a `SELECT 1` if we see false-positive ready.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Auth smoke test — echoes the verified claims (minus secrets).
         *
         *     Useful during Phase 0 deployment to confirm the JWT secret and
         *     the Authorization-header plumbing work end-to-end before any
         *     real endpoints exist. Deliberately under `/v1` so the prefix
         *     convention exists from day one.
         */
        get: operations["whoami_v1_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** ReadinessChecks */
        ReadinessChecks: {
            /** Supabase Url Configured */
            supabase_url_configured: boolean;
            /** Supabase Db Configured */
            supabase_db_configured: boolean;
            /** Jwt Secret Configured */
            jwt_secret_configured: boolean;
            /** Db Pool Open */
            db_pool_open: boolean;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Status */
            status: string;
            checks: components["schemas"]["ReadinessChecks"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhoAmIResponse */
        WhoAmIResponse: {
            /** User Id */
            user_id: string | null;
            /** Role */
            role: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    whoami_v1_whoami_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
