// Auto-generated from services/agent-py/openapi.json. Do not edit by hand.
// Regenerate with: bun run codegen:agent-types
// See scripts/codegen-agent-types.sh for the rationale.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe — returns 200 as long as the process is up.
         *
         *     Does NOT depend on Supabase, the model gateway, or any other
         *     external service. A failing /healthz means restart the container;
         *     a failing /readyz means *don't route traffic yet* but the process
         *     might recover on its own.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness probe — reports configured dependencies.
         *
         *     Phase 0 only reported config presence; Phase 1 additionally
         *     reports whether the Postgres pool is open (which is the closest
         *     we get to "Postgres reachable" without a per-request `SELECT 1`).
         *     Phase 2+ may add a `SELECT 1` if we see false-positive ready.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract
         * @description Extract text from an uploaded file. Mirrors
         *     `app/api/extract/route.ts` — accepts multipart/form-data with
         *     a `file` field and returns a structured `ExtractionResponse`
         *     matching `ExtractionResponseSchema` on the TS side.
         *
         *     Auth-protected (JWT) — Phase 4 cuts the frontend over to this
         *     endpoint, at which point the existing Next.js route can be
         *     deleted. Until then both producers exist and the wire schema
         *     keeps them aligned.
         *
         *     File-size cap matches the Next.js side (`FILE_SIZE_LIMIT` in
         *     `lib/shared/upload-config.ts`); FastAPI enforces multipart size
         *     at the framework level. A read failure surfaces as 500 with
         *     the parser's error message so the frontend can show it to the
         *     user without trying to recover.
         */
        post: operations["extract_v1_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Streaming chat endpoint — Phase 4-1 of PLAN-agent-api.
         *
         *     Mirrors `app/api/chat/route.ts` on the TS side. Accepts a
         *     narrow request (messages + model + optional system prompt
         *     + optional max_tokens) and streams Anthropic deltas back as
         *     SSE frames.
         *
         *     Wire format is selectable via the `?format=` query parameter:
         *
         *       - `format=custom` (default) — `{type:"text|error|done"}`
         *         frames that match the existing Next.js chat consumer
         *         (`use-chat-send.ts`). Phase 4-1 + 4-2 baseline so the
         *         selector can swap between TS and Python without changing
         *         the consumer.
         *
         *       - `format=ai-sdk` — Phase 3g — AI SDK v5 UI message stream
         *         (`start`/`text-start`/`text-delta`/`text-end`/`finish` +
         *         `[DONE]` terminator), so a consumer using
         *         `@ai-sdk/react`'s `useChat()` can read Python output
         *         natively. Response adds the
         *         `x-vercel-ai-ui-message-stream: v1` header the SDK uses
         *         to advertise its protocol version.
         *
         *     Phase 4-1 is **text-only**: tools / skills / attachments /
         *     MCP all deferred. The Python service already has the
         *     agent-loop machinery for tool use (Phase 2b-2 + 3c+);
         *     wiring it into the streaming chat path lands in Phase 4-3+.
         *
         *     Returns 503 when `ANTHROPIC_API_KEY` is unset — fast-fail
         *     signal to monitoring that the deploy is misconfigured rather
         *     than a silent stub response.
         */
        post: operations["chat_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/url/fetch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Url Fetch
         * @description Fetch + extract a URL as a bookmark snapshot. Phase 4-4-a
         *     of PLAN-agent-api — Python mirror of `app/api/url/fetch/route.ts`.
         *
         *     Pipeline:
         *       1. Normalise the URL (prepend https:// for bare-domain
         *          input, lowercase host, strip fragment).
         *       2. SSRF gate — scheme allowlist, textual hostname blocklist,
         *          DNS rebinding defence (resolve + private-IP check).
         *       3. Fetch with 10s timeout, manual redirect handling (5 hops
         *          max, each re-validated), 5 MB body cap.
         *       4. Extract title / content / description / favicon via lxml.
         *
         *     Error → status mapping mirrors the TS path: validation /
         *     unsupported_content_type → 400, timeout → 408, body_too_large
         *     → 413, http_error / too_many_redirects / network → 502.
         */
        post: operations["url_fetch_v1_url_fetch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images/refresh-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Images Refresh Url
         * @description Re-sign an expired generated-image URL. Phase 4-4-a of
         *     PLAN-agent-api — Python mirror of
         *     `app/api/images/refresh-url/route.ts`.
         *
         *     Authorisation: the bucket layout is `<user_id>/...` (see
         *     `0003_storage.sql`); we reject any `storage_path` whose first
         *     segment doesn't match the JWT's `sub` claim before touching
         *     Storage. RLS would also reject the call but a clean 403 is
         *     friendlier than fighting an opaque Storage error.
         *
         *     Returns 404 when the object doesn't exist OR Storage isn't
         *     configured (both look the same from the API's perspective).
         */
        post: operations["images_refresh_url_v1_images_refresh_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize
         * @description Summarisation endpoint — Phase 4-4b of PLAN-agent-api.
         *     Python mirror of `app/api/summarize/route.ts`.
         *
         *     Four modes via discriminated union on `mode`: file /
         *     conversation / compress / project-breakdown. Three return
         *     JSON; compress returns `{recap: str}` markdown.
         *
         *     Notable difference from TS: this endpoint only talks to
         *     Anthropic (no Vercel-gateway routing). When the caller's
         *     `model` doesn't look like an Anthropic id (e.g. the TS
         *     default `google/gemini-2.5-flash`), we fall back to
         *     `claude-3-5-haiku-20241022`. Caller behaviour is unaffected
         *     because the field is still accepted; the TS-shape body comes
         *     through unchanged.
         */
        post: operations["summarize_v1_summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mcp/{server_id}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mcp Proxy
         * @description MCP proxy — Phase 4-4b of PLAN-agent-api. Python mirror of
         *     `app/api/mcp/[serverId]/[action]/route.ts`.
         *
         *     Actions:
         *       - `discover` → returns `{capabilities}` from the MCP
         *         handshake (tools / resources / prompts).
         *       - `call` → invokes a tool, returns `{result: {text,
         *         is_error}}`.
         *       - `read` → reads a resource by URI, returns `{result:
         *         {text?, mime_type?}}`.
         *
         *     Credentials come from two places:
         *       1. `X-MCP-Credentials` header (local-mode — the client
         *          attaches the cred from localStorage). Decoded as
         *          base64-JSON, same shape the TS path expects.
         *       2. Cloud-mode fallback when no header — looks up the
         *          server row by id under per-user RLS impersonation,
         *          decrypts the credential via the SECURITY DEFINER RPC.
         *
         *     If neither produces a credential and the upstream MCP server
         *     actually requires auth, the call fails upstream and the
         *     proxy surfaces it as 502 — same as TS.
         */
        post: operations["mcp_proxy_v1_mcp__server_id___action__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Auth smoke test — echoes the verified claims (minus secrets).
         *
         *     Useful during Phase 0 deployment to confirm the JWT secret and
         *     the Authorization-header plumbing work end-to-end before any
         *     real endpoints exist. Deliberately under `/v1` so the prefix
         *     convention exists from day one.
         */
        get: operations["whoami_v1_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_extract_v1_extract_post */
        Body_extract_v1_extract_post: {
            /**
             * File
             * @description The uploaded file to extract text from.
             */
            file: string;
        };
        /**
         * BookmarkSnapshotModel
         * @description Mirrors `BookmarkSnapshot` in `lib/server/url/fetch.ts`. Kept
         *     snake_case on the wire to match the rest of the Python service's
         *     convention (see `ExtractionResponse.full_text`).
         */
        BookmarkSnapshotModel: {
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /** Content Truncated */
            content_truncated: boolean;
            /** Content Hash */
            content_hash: string;
            /** Description */
            description?: string | null;
            /** Favicon Url */
            favicon_url?: string | null;
        };
        /**
         * ChatMessageRequest
         * @description One message in the chat history. Tight: role is restricted to
         *     `user` / `assistant`, content is a flat string. The TS chat schema
         *     supports multimodal content parts; the Python endpoint accepts a
         *     narrower shape for now and grows it when tool support lands
         *     (Phase 4-2).
         */
        ChatMessageRequest: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /**
         * ChatRequest
         * @description Wire shape for POST /v1/chat. Mirrors the subset of
         *     `ChatRequestSchema` (TS) we honour today — messages + model +
         *     workspaceSystemPrompt + maxSteps proxied as `max_tokens`. Skills /
         *     attachments / MCP / referenceImage deferred.
         *
         *     Phase 4-3 adds `enable_tools` (opt-in): when true, the route
         *     registers the built-in tool set (`webFetch`, plus the
         *     `TAVILY_API_KEY`/`MINIMAX_CN_API_KEY`-gated tools) and loops
         *     `messages.stream` + tool execution. Default false keeps the
         *     text-only Phase 4-1 behaviour.
         */
        ChatRequest: {
            /** Messages */
            messages: components["schemas"]["ChatMessageRequest"][];
            /** Model */
            model: string;
            /** System */
            system?: string | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /**
             * Enable Tools
             * @default false
             */
            enable_tools: boolean;
            /** Max Steps */
            max_steps?: number | null;
        };
        /** CompressSummariseBody */
        CompressSummariseBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "compress";
            /** Messages */
            messages: components["schemas"]["SummariseMessage"][];
            /** Model */
            model?: string | null;
        };
        /** ConversationSummariseBody */
        ConversationSummariseBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "conversation";
            /** Messages */
            messages: components["schemas"]["SummariseMessage"][];
            /** Model */
            model?: string | null;
        };
        /**
         * ExtractionResponse
         * @description Mirrors `ExtractionResponseSchema` in
         *     `lib/shared/api-schemas.ts` for kind / text / truncated / language.
         *     Keeps snake_case on `full_text` to match the rest of the Python
         *     service's wire format (see `WhoAmIResponse.user_id`); the
         *     generated TS types reflect that so the Phase 4 cutover doesn't
         *     have to recase fields.
         */
        ExtractionResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "pdf" | "docx" | "markdown" | "csv" | "json" | "text" | "image" | "html" | "code" | "spreadsheet" | "unsupported";
            /** Text */
            text: string;
            /** Truncated */
            truncated: boolean;
            /** Full Text */
            full_text?: string | null;
            /** Language */
            language?: string | null;
        };
        /** FileSummariseBody */
        FileSummariseBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "file";
            /** Name */
            name?: string | null;
            /** Text */
            text: string;
            /** Model */
            model?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /**
         * McpProxyBody
         * @description One body shape for all three actions. `tool` is required for
         *     `call`, `uri` for `read`; the route validates per-action.
         */
        McpProxyBody: {
            server: components["schemas"]["McpServerBody"];
            /** Tool */
            tool?: string | null;
            /** Input */
            input?: {
                [key: string]: unknown;
            } | null;
            /** Uri */
            uri?: string | null;
        };
        /**
         * McpServerBody
         * @description Subset of `McpServer` the proxy actually needs. Mirrors the
         *     TS `ServerSchema` in the route. Transport is fixed at `http`
         *     matching the DB CHECK constraint.
         */
        McpServerBody: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Transport
             * @default http
             * @constant
             */
            transport: "http";
        };
        /** ProjectBreakdownBody */
        ProjectBreakdownBody: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            mode: "project-breakdown";
            /** Goal */
            goal: string;
            /** Existingtitles */
            existingTitles?: string[] | null;
            /** Model */
            model?: string | null;
        };
        /** ReadinessChecks */
        ReadinessChecks: {
            /** Supabase Url Configured */
            supabase_url_configured: boolean;
            /** Supabase Db Configured */
            supabase_db_configured: boolean;
            /** Jwt Secret Configured */
            jwt_secret_configured: boolean;
            /** Db Pool Open */
            db_pool_open: boolean;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Status */
            status: string;
            checks: components["schemas"]["ReadinessChecks"];
        };
        /**
         * RefreshImageUrlRequest
         * @description Mirrors `RefreshImageUrlRequestSchema` in
         *     `lib/shared/api-schemas.ts`. The TS field is `storagePath`; the
         *     Python wire uses `storage_path` to match the rest of the
         *     service's convention.
         */
        RefreshImageUrlRequest: {
            /** Storage Path */
            storage_path: string;
        };
        /** RefreshImageUrlResponse */
        RefreshImageUrlResponse: {
            /** Url */
            url: string;
        };
        /** SummariseMessage */
        SummariseMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /**
         * UrlFetchRequest
         * @description Mirrors the TS `{ url }` body schema. Length capped to defeat
         *     pathological inputs — the SSRF gate runs after this.
         */
        UrlFetchRequest: {
            /** Url */
            url: string;
        };
        /** UrlFetchResponse */
        UrlFetchResponse: {
            /** Ok */
            ok: boolean;
            bookmark: components["schemas"]["BookmarkSnapshotModel"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhoAmIResponse */
        WhoAmIResponse: {
            /** User Id */
            user_id: string | null;
            /** Role */
            role: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    extract_v1_extract_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_v1_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_v1_chat_post: {
        parameters: {
            query?: {
                format?: "custom" | "ai-sdk";
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    url_fetch_v1_url_fetch_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UrlFetchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlFetchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    images_refresh_url_v1_images_refresh_url_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshImageUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshImageUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_v1_summarize_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileSummariseBody"] | components["schemas"]["ConversationSummariseBody"] | components["schemas"]["CompressSummariseBody"] | components["schemas"]["ProjectBreakdownBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_proxy_v1_mcp__server_id___action__post: {
        parameters: {
            query?: never;
            header?: {
                "X-MCP-Credentials"?: string | null;
                authorization?: string | null;
            };
            path: {
                server_id: string;
                action: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["McpProxyBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami_v1_whoami_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmIResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
