import type { Metadata } from "next";
import { Manrope, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeApplier } from "@/components/theme-applier";
import { TooltipProvider } from "@/components/ui/tooltip";

// Runs before React hydrates so the initial paint already has the correct
// theme class. Mirrors the resolver in components/theme-applier.tsx.
// Keep in sync with the zustand persist key in lib/hooks/use-store.ts.
const themeBootstrapScript = `(function(){try{var s=localStorage.getItem('hummingbird-storage');var t='dark';if(s){var p=JSON.parse(s);if(p&&p.state&&p.state.theme)t=p.state.theme;}var d=t==='dark'||(t==='system'&&window.matchMedia('(prefers-color-scheme: dark)').matches);if(d)document.documentElement.classList.add('dark');}catch(e){}})();`

const manropeSans = Manrope({
  variable: "--font-manrope-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hummingbird",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeBootstrapScript }} />
      </head>
      <body
        className={`${manropeSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeApplier />
        <TooltipProvider delayDuration={150}>{children}</TooltipProvider>
      </body>
    </html>
  );
}
