#!/bin/bash
# Supabase types ↔ migrations alignment check.
#
# `lib/shared/supabase/types.ts` is regenerated by `bun run supabase:types`
# (which calls `supabase gen types typescript --local` against a running
# local Supabase stack). Whenever you add or change a migration under
# `supabase/migrations/`, the generated types file needs to be regenerated
# alongside — otherwise the typed `SupabaseClient<Database>` instances
# silently fall behind the actual schema, masking bugs as `any` or
# producing confusing typecheck errors.
#
# This script is the CI gate that catches "you forgot to regen": if a
# pushed branch touches any file under `supabase/migrations/` but doesn't
# also touch `lib/shared/supabase/types.ts`, it fails with a clear
# remediation message.
#
# It's deliberately lightweight — no `supabase start`, no docker pull,
# no full type regeneration. Booting the Supabase stack in CI adds
# ~60s + a heavy image pull on every PR, for a check that mostly just
# enforces a workflow discipline. The lightweight version catches the
# common failure mode (forgetting to regen) without the infrastructure
# cost. A real "did codegen run correctly" check would be a follow-up.
#
# Run locally:
#   bash scripts/verify-supabase-types.sh <base-ref>
#
# CI invokes it with the PR base branch as `$1`.

set -uo pipefail

BASE_REF="${1:-origin/dev}"
MIGRATIONS_DIR="supabase/migrations"
TYPES_FILE="lib/shared/supabase/types.ts"

# What changed between the PR base and HEAD?
CHANGED=$(git diff --name-only "$BASE_REF...HEAD" 2>/dev/null)
if [ -z "$CHANGED" ]; then
  # No diff or comparison failed (e.g. base ref missing locally). Nothing
  # to check — exit clean rather than spuriously failing.
  exit 0
fi

if ! echo "$CHANGED" | grep -q "^$MIGRATIONS_DIR/"; then
  # Migrations untouched → no alignment requirement.
  exit 0
fi

if echo "$CHANGED" | grep -q "^$TYPES_FILE\$"; then
  # Both touched → the convention is satisfied. (We can't actually verify
  # the regen was correct without running it, but the diff-pairing
  # discipline catches the "forgot entirely" case.)
  exit 0
fi

# Allow an explicit opt-out for migrations that don't change generated
# types — e.g. enabling a Realtime publication on an existing table,
# granting RPC privileges, swapping an index. A first-line marker
# (`-- verify-supabase-types: skip`) in EVERY new/changed migration of
# the PR opts the whole pairing out. The grep keeps this enforceable:
# missing the marker on any one of them re-engages the check.
ONLY_SKIPPABLE=true
for f in $(echo "$CHANGED" | grep "^$MIGRATIONS_DIR/" || true); do
  if [ ! -f "$f" ]; then
    # File was deleted in this PR — don't try to read it.
    ONLY_SKIPPABLE=false
    break
  fi
  if ! head -1 "$f" | grep -qiE '^--[[:space:]]*verify-supabase-types:[[:space:]]*skip'; then
    ONLY_SKIPPABLE=false
    break
  fi
done
if [ "$ONLY_SKIPPABLE" = "true" ]; then
  echo "✓ Supabase types alignment skipped (all changed migrations carry the opt-out marker)."
  exit 0
fi

# Migrations changed; types didn't. Fail loudly with instructions.
cat >&2 <<EOF
✗ Supabase types alignment check failed

  Files under \`$MIGRATIONS_DIR/\` were changed in this PR, but
  \`$TYPES_FILE\` was not.

  The generated types file must be regenerated alongside any schema
  change so the typed Supabase client stays in sync with the actual
  schema. Run:

      bun run supabase:start    # if not already running
      bun run supabase:reset    # re-applies all migrations to local DB
      bun run supabase:types    # regenerates lib/shared/supabase/types.ts

  Then commit \`$TYPES_FILE\` alongside your migration.

  Changed files in this PR:
$(echo "$CHANGED" | sed 's/^/    /')
EOF
exit 1
