#!/bin/bash
# Supabase types ↔ migrations alignment check.
#
# `lib/shared/supabase/types.ts` is regenerated by `bun run supabase:types`
# (which calls `supabase gen types typescript --local` against a running
# local Supabase stack). Whenever you add or change a migration under
# `supabase/migrations/`, the generated types file needs to be regenerated
# alongside — otherwise the typed `SupabaseClient<Database>` instances
# silently fall behind the actual schema, masking bugs as `any` or
# producing confusing typecheck errors.
#
# This script is the CI gate that catches "you forgot to regen": if a
# pushed branch ADDS or MODIFIES a migration under `supabase/migrations/`
# but doesn't also touch `lib/shared/supabase/types.ts`, it fails with a
# clear remediation message.
#
# Pure renames and deletions are exempt: shuffling a migration's filename
# (e.g. resolving a number collision) or removing one changes no schema
# shape, so codegen output is unaffected and `types.ts` legitimately
# needs no update. Only Added (A) / Modified (M) migration files require
# a paired types regen — detected via `git diff --diff-filter=AM`.
#
# It's deliberately lightweight — no `supabase start`, no docker pull,
# no full type regeneration. Booting the Supabase stack in CI adds
# ~60s + a heavy image pull on every PR, for a check that mostly just
# enforces a workflow discipline. The lightweight version catches the
# common failure mode (forgetting to regen) without the infrastructure
# cost. A real "did codegen run correctly" check would be a follow-up.
#
# Run locally:
#   bash scripts/verify-supabase-types.sh <base-ref>
#
# CI invokes it with the PR base branch as `$1`.

set -uo pipefail

BASE_REF="${1:-origin/dev}"
MIGRATIONS_DIR="supabase/migrations"
TYPES_FILE="lib/shared/supabase/types.ts"

# Added/modified migrations between the PR base and HEAD. `--diff-filter=AM`
# excludes pure renames (R) and deletions (D) — those don't alter schema
# shape, so they don't require a types regen.
MIGRATIONS_AM=$(git diff --name-only --diff-filter=AM "$BASE_REF...HEAD" \
  -- "$MIGRATIONS_DIR" 2>/dev/null)
if [ -z "$MIGRATIONS_AM" ]; then
  # No added/changed migrations (none at all, or only renames/deletes) →
  # no alignment requirement. Also covers the base-ref-missing case (the
  # diff returns empty), exiting clean rather than spuriously failing.
  exit 0
fi

# Full changed-file list, used for the types-file check + the diagnostic.
CHANGED=$(git diff --name-only "$BASE_REF...HEAD" 2>/dev/null)

if echo "$CHANGED" | grep -q "^$TYPES_FILE\$"; then
  # Both touched → the convention is satisfied. (We can't actually verify
  # the regen was correct without running it, but the diff-pairing
  # discipline catches the "forgot entirely" case.)
  exit 0
fi

# A migration was added/changed; types didn't move. Fail loudly.
cat >&2 <<EOF
✗ Supabase types alignment check failed

  These migrations were added or modified, but
  \`$TYPES_FILE\` was not:

$(echo "$MIGRATIONS_AM" | sed 's/^/    /')

  The generated types file must be regenerated alongside any schema
  change so the typed Supabase client stays in sync with the actual
  schema. Run:

      bun run supabase:start    # if not already running
      bun run supabase:reset    # re-applies all migrations to local DB
      bun run supabase:types    # regenerates lib/shared/supabase/types.ts

  Then commit \`$TYPES_FILE\` alongside your migration.

  Changed files in this PR:
$(echo "$CHANGED" | sed 's/^/    /')
EOF
exit 1
