-- Phase 2 of the prompt library plan
-- (`docs/PLAN-prompt-library.md`). Phase 1 shipped the in-Zustand
-- store + UI; this migration adds the durable Supabase mirror so
-- prompts roam across devices via the existing sync layer.
--
-- Shape mirrors the Phase 2 sketch in the plan:
--   - User-scoped (no `workspace_id`) — same intent as MCP local
--     credentials, opposite of MCP server rows. A user's prompts
--     follow them across workspaces.
--   - Soft-delete via `deleted_at` so the diff handler can ship
--     tombstones without special-casing in the UI.
--   - `slug` is unique per user, but only for *live* rows
--     (`deleted_at is null`). A user can re-use a slug after they
--     soft-delete the previous holder; restore brings the old row
--     back to active and the unique index re-arms.
--   - `id` is `text` (not `uuid`) to match the in-store id —
--     `Prompt.id` is generated by the existing `uuid()` helper and
--     ends up looking like a uuid, but the migration keeps the
--     column loose so we don't have to coerce on every upsert. All
--     other tables in this codebase mix `uuid` and `text` ids
--     (e.g. MCP server ids are `text`); this matches that posture.
--
-- RLS is the boilerplate own-your-rows pattern — same four-policy
-- shape as every other table in `0002_rls_policies.sql`.
--
-- Idempotent: `if not exists` on the table; policies are created
-- inside a DO block that swallows the duplicate-policy error. Safe
-- to re-run after a partial apply.

create table if not exists prompts (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  slug text not null,
  template text not null,
  variables text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index if not exists prompts_user_slug_unique
  on prompts (user_id, slug)
  where deleted_at is null;

create index if not exists prompts_user_updated_idx
  on prompts (user_id, updated_at desc);

alter table prompts enable row level security;

do $$ begin
  create policy "prompts: select own"
    on prompts for select using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "prompts: insert own"
    on prompts for insert with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "prompts: update own"
    on prompts for update using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "prompts: delete own"
    on prompts for delete using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
