-- Custom agents / personas (PLAN-custom-agents.md). A persona is a
-- saved bundle of { name, system prompt, model, allowed skills,
-- allowed MCP servers } invoked via `/<slug>` from the chat input.
--
-- Workspace-scoped (mirrors the post-0017 prompts table). The same
-- four-policy own-your-rows RLS shape as every other table in
-- `0002_rls_policies.sql`. Soft-delete via `deleted_at` so the diff
-- handler can ship tombstones without special-casing in the UI.
--
-- `id` is `text` (not `uuid`) to match the in-store id — `Agent.id`
-- is generated by the existing `uuid()` helper and looks like a uuid,
-- but the column stays loose so we don't coerce on every upsert.
-- Matches the prompts / mcp_servers posture.
--
-- `slug` is unique per (workspace, !deleted_at) — a user can re-use a
-- slug after soft-deleting the previous holder.
--
-- `allowed_skill_ids` / `allowed_mcp_server_ids` are TEXT[] (Postgres
-- array) because both id spaces are loose strings (skill ids are
-- `'webSearch' | 'webFetch' | 'imageGen' | 'searchFiles'` per the
-- shared SkillId union; MCP server ids are user-supplied text from
-- the mcp_servers table). No FKs on the MCP allow-list — an MCP
-- server can be deleted independently and the persona keeps its
-- (now stale) reference, which the worker silently drops.
--
-- Idempotent: `if not exists` on the table; policies created inside
-- a DO block that swallows the duplicate-policy error. Safe to re-run.

create table if not exists agents (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  workspace_id uuid not null references workspaces(id) on delete cascade,
  name text not null,
  slug text not null,
  system_prompt text not null default '',
  model_id text,
  allowed_skill_ids text[] not null default '{}',
  allowed_mcp_server_ids text[] not null default '{}',
  icon text,
  pinned boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index if not exists agents_workspace_slug_unique
  on agents (workspace_id, slug)
  where deleted_at is null;

create index if not exists agents_workspace_updated_idx
  on agents (workspace_id, updated_at desc);

alter table agents enable row level security;

do $$ begin
  create policy "agents: select own"
    on agents for select using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "agents: insert own"
    on agents for insert with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "agents: update own"
    on agents for update using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "agents: delete own"
    on agents for delete using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;
