import "server-only"

/**
 * Follow-up suggestion chips. Generated by a cheap second model call
 * after the main chat turn completes. The model is asked for strict
 * JSON; `parseSuggestionsJson` is permissive about markdown fences
 * around it and clamps the result to 3 short strings.
 *
 * Decoration only — every failure path returns an empty array. The
 * route never blocks a chat turn on suggestion generation.
 *
 * Mirrors `services/agent-py/src/agent_py/chat.py:generate_chat_suggestions`
 * and `services/agent-ts/src/chat.ts:generateChatSuggestions`. Same
 * JSON contract, same caps.
 */

import { generateText, type ModelMessage } from "ai"

import { selectModel } from "@/server/model-provider"

import { lastUserText } from "./prompt-builders"

const SUGGESTION_MODEL = "google/gemini-2.5-flash"

const FENCE_HEAD_RE = /^```(?:json)?\s*\n?/
const FENCE_TAIL_RE = /\n?```\s*$/

/** Strip markdown fences the model occasionally wraps JSON in, then
 *  parse + validate as a flat string array. Returns at most 3 short
 *  non-empty entries. Permissive — any decode failure yields an empty
 *  array. */
export function parseSuggestionsJson(raw: string): string[] {
  const cleaned = raw.trim().replace(FENCE_HEAD_RE, "").replace(FENCE_TAIL_RE, "").trim()
  try {
    const parsed = JSON.parse(cleaned) as unknown
    if (!Array.isArray(parsed)) return []
    return parsed
      .filter((s): s is string => typeof s === "string")
      .map((s) => s.trim())
      .filter((s) => s.length > 0 && s.length <= 120)
      .slice(0, 3)
  } catch {
    return []
  }
}

/** Generate up to 3 follow-up chips for the current turn. Returns
 *  an empty array on any failure — chips are decoration; failures
 *  must never block a chat turn. */
export async function generateSuggestions(
  history: ModelMessage[],
  assistantReply: string,
  signal: AbortSignal,
): Promise<string[]> {
  const userText = lastUserText(history)
  const prompt = `Based on this exchange, propose 3 concise follow-up questions the user might want to ask next. Each must be under 14 words, in the user's voice (not "ask the user…"). Reply with strict JSON only — a flat array of 3 strings, no prose:
["...", "...", "..."]

User asked:
"""
${userText.slice(0, 4000)}
"""

Assistant answered:
"""
${assistantReply.slice(0, 4000)}
"""`

  try {
    const result = await generateText({
      abortSignal: signal,
      model: selectModel(SUGGESTION_MODEL),
      prompt,
      maxOutputTokens: 200,
      temperature: 0.7,
    })
    return parseSuggestionsJson(result.text)
  } catch {
    return []
  }
}
