import "server-only"

/**
 * Follow-up suggestion chips. Generated by a cheap second model call
 * after the main chat turn completes. The model is asked for strict
 * JSON; `parseSuggestionsJson` is permissive about markdown fences
 * around it and clamps the result to 3 short strings.
 *
 * Decoration only — every failure path returns an empty array. The
 * route never blocks a chat turn on suggestion generation.
 *
 * Mirrors `services/agent-py/src/agent_py/chat.py:generate_chat_suggestions`
 * and `services/agent-ts/src/chat.ts:generateChatSuggestions`. Same
 * JSON contract, same caps.
 */

import { generateText, type ModelMessage } from "ai"
import { z } from "zod"

import { generateStructured } from "@/server/ai/structured"
import { selectModel } from "@/server/model-provider"
import { modelSupportsStructuredOutput } from "@/shared/models"
import {
  clampSuggestions,
  parseSuggestionsJson,
} from "@/shared/suggestions-parser"

import { lastUserText } from "./prompt-builders"

// Re-export so existing callers / tests keep their imports stable.
export { parseSuggestionsJson }

const SUGGESTION_MODEL = "google/gemini-2.5-flash"

// Structured-output shape. The model returns an object (top-level arrays
// aren't portable across providers); we clamp the array to the wire
// contract afterwards. The prompt still asks for a flat array — harmless
// for the structured path (the schema governs) and required by the
// lenient fallback's `parseSuggestionsJson`.
const SuggestionsSchema = z.object({ suggestions: z.array(z.string()).max(8) })

/** Generate up to 3 follow-up chips for the current turn. Returns
 *  an empty array on any failure — chips are decoration; failures
 *  must never block a chat turn. */
export async function generateSuggestions(
  history: ModelMessage[],
  assistantReply: string,
  signal: AbortSignal,
): Promise<string[]> {
  const userText = lastUserText(history)
  const prompt = `Based on this exchange, propose 3 concise follow-up questions the user might want to ask next. Each must be under 14 words, in the user's voice (not "ask the user…"). Reply with strict JSON only — a flat array of 3 strings, no prose:
["...", "...", "..."]

User asked:
"""
${userText.slice(0, 4000)}
"""

Assistant answered:
"""
${assistantReply.slice(0, 4000)}
"""`

  try {
    // Structured path for models that support it — guaranteed schema-valid
    // output, no fishing JSON out of prose.
    if (modelSupportsStructuredOutput(SUGGESTION_MODEL)) {
      try {
        const { suggestions } = await generateStructured({
          modelId: SUGGESTION_MODEL,
          schema: SuggestionsSchema,
          prompt,
          abortSignal: signal,
          maxOutputTokens: 200,
          temperature: 0.7,
        })
        return clampSuggestions(suggestions)
      } catch {
        // Fall through to the lenient text path (also covers a provider
        // without a configured key — the retry below fails the same way
        // and the outer catch returns []).
      }
    }
    const result = await generateText({
      abortSignal: signal,
      model: selectModel(SUGGESTION_MODEL),
      prompt,
      maxOutputTokens: 200,
      temperature: 0.7,
    })
    return parseSuggestionsJson(result.text)
  } catch {
    return []
  }
}
